#cloud-config
users:
  - name: kupriyanov
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGS8nVF3ee5UJiBR/r4CAo7uUY71TZXJQbTpBhhdql1h kupriyanov@diploma

package_update: true
package_upgrade: true
