# Определяем пользователя
ansible_ssh_user: kupriyanov

# Настройки аутентификации на Zabbix-Server
zabbix_db_user: zabbix
zabbix_db_password: Password
zabbix_db_name: zabbix

# переменные Ansible для установки Elasticsearch из зеркала Яндекса
es_version: 7
yandex_mirror_url: https://mirror.yandex.ru/mirrors/elastic/{{ es_version }}/ stable main

# Переменные для filebeat
elasticsearch_ip: 10.10.1.20
kibana_ip: 46.21.245.86
