[all:vars]
ansible_user=kupriyanov
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o ProxyCommand="ssh -p 22 -W %h:%p -q kupriyanov@158.160.56.2"'

application-load-balancer=158.160.224.244:80

bastion=158.160.56.2
  
weba=10.10.1.28
webb=10.10.2.10

elasticsearch=10.10.1.7

zabbix-server=93.77.178.134

kibana-server=158.160.60.111


[bastion]
bastion-server ansible_host=bastion.ru-central1.internal

[elasticsearch-server]
elasticsearch ansible_host=elasticsearch.ru-central1.internal

[kibana]
kibana-server ansible_host=kibana-server.ru-central1.internal

[hosts]
weba ansible_host=weba.ru-central1.internal
webb ansible_host=webb.ru-central1.internal
  
[monitoring]
zabbix-server ansible_host=zabbix-server.ru-central1.internal
