---
- name: Install Kibana from Yandex Mirror
  hosts: kibana_servers
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    # Установка зависимостей
    - name: Install required packages
      apt:
        name:
          - libnss3
          - apache2
          - libwww-perl
          - openjdk-11-jre
        state: present
        update_cache: yes

    # Добавление репозитория Elasticsearch из зеркала Yandex
    - name: Add Yandex mirror repository for Kibana
      apt_repository:
        repo: "deb [trusted=yes] {{ yandex_mirror_url }}"
        state: present
        filename: elasticsearch
        update_cache: yes

    # Установка Kibana
    - name: Install Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes

    # Создание директории для конфигов (если отсутствует)
    - name: Create Kibana config directory
      file:
        path: /etc/kibana
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Копирование конфигурационного файла Kibana
    - name: Copy Kibana config file
      copy:
        src: configs/kibana/config.yml
        dest: /etc/kibana/kibana.yml
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: restart kibana

    # Настройка прав на директорию Kibana
    - name: Set correct permissions for Kibana directory
      file:
        path: /etc/kibana
        state: directory
        owner: root
        group: root
        mode: '0755'

    # Настройка Kibana для работы с Elasticsearch по внутреннему IP
    - name: Configure Kibana Elasticsearch URL
      ansible.builtin.lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?elasticsearch.hosts:'
        line: 'elasticsearch.hosts: ["http://{{ hostvars["elasticsearch"].ansible_host }}:9200"]'   # Берется из инвентаря
        backup: yes
      notify: restart kibana

    # Настройка внешнего доступа (слушаем все интерфейсы)
    - name: Configure Kibana server host
      ansible.builtin.lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server.host:'
        line: 'server.host: "0.0.0.0"'
        backup: yes
      notify: restart kibana

    # Настройка порта Kibana
    - name: Configure Kibana server port
      ansible.builtin.lineinfile:
        path: /etc/kibana/kibana.yml
        regexp: '^#?server.port:'
        line: 'server.port: 5601'
        backup: yes
      notify: restart kibana

    # Перезагрузка systemd
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    # Включение и запуск Kibana
    - name: Enable and start Kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: restart kibana
      systemd:
        name: kibana
        state: restarted
        daemon_reload: yes
