---
- name: Install Kibana from Yandex Mirror
  hosts: kibana-server
  become: true
  vars_files:
    - "./vars/main.yml"
  tasks:

# Установка пакетов
    - name: install packages
      apt:
        name:
          - libnss3 #библиотека Network Security Services (NSS) от Mozilla
          - apache2 #веб-сервер Apache HTTP Server
          - libwww-perl #набор Perl-модулей для работы с HTTP/HTTPS (LWP)
          - openjdk-11-jre #Java Runtime Environment (версия 11) с графическим интерфейсом
        state: present
        update_cache: yes

# Добавление репозитория из зеркала Yandex mirror
    - name: Добавление Yandex mirror в репозиторий
      apt_repository:
        repo: "deb [trusted=yes] {{ yandex_mirror_url }}"
        state: present
        filename: elasticsearch

# Установка Kibana из добавленного репозитория
    - name: Установка Kibana
      apt:
        name: kibana
        state: present
        update_cache: yes

# Добавление настроек Kibana
    - name: Copy Kibana config file
      copy:
        src: ./configs/kibana/config.yml
        dest: /etc/kibana/kibana.yml

# Включение и запуск kibana
    - name: Включение и запуск kibana
      systemd:
        name: kibana
        enabled: yes
        state: started
        daemon_reload: true
