---
- name: install nginx
  hosts: webb
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install nginx and net-tools
      apt:
        name:
          - nginx
          - net-tools
        state: present
        update_cache: yes

    - name: Copy index.nginx.html for webb
      copy:
        src: webb_index/index.nginx.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: reload nginx

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
